on:
  pull_request:
    types: [opened, unopened, synchronize]

jobs:
  pull-request-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Pull artifacts
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.PAT }}
          GITHUB_REPOSITORY: ${{ github.event.repository.name }}
          GITHUB_HEAD_REF: ${{ github.event.pull_request.head.ref }}
        run: python pull_artifacts.py 
        
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: static-site
          
      - name: Test artifact download
        run: ls -R
